DROP TABLE IF EXISTS API_USER;
DROP TABLE IF EXISTS API_PHONE;

CREATE TABLE API_USER(
	US_ID VARCHAR(250) PRIMARY KEY,
	US_NAME VARCHAR(250),
	US_EMAIL VARCHAR(250),
	US_PASSWORD VARCHAR(250),
	US_CREATE TIMESTAMP,
	US_MODIFIED TIMESTAMP,
	US_LAST_LOGIN TIMESTAMP,
	US_IS_ACTIVE BOOLEAN
	--US_TOKEN VARCHAR(250),
);

CREATE TABLE API_PHONE(
	PH_ID AUTO_INCREMENT NUMBER PRIMARY KEY,
	PH_NUMBER NUMBER,
	PH_CITY_CODE NUMBER,
	PH_COUNTRY_CODE NUMBER,
	US_ID VARCHAR(250)
);